//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приемная_комиссия
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int Id { get; set; }
        public string Point { get; set; }
        public int Prioritet { get; set; }
    
        public virtual Entrant Entrant { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
